#!/usr/bin/env bash
set -euo pipefail

project_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
source "${project_root}/scripts/chipyard_paths.sh"
chipyard_root=$(agentsys_chipyard_root "${project_root}")
verify_only=0

if [[ ${1:-} == --verify-only ]]; then
  verify_only=1
elif [[ $# -ne 0 ]]; then
  echo "usage: $0 [--verify-only]" >&2
  exit 2
fi

agentsys_require_chipyard_source "${chipyard_root}"

ensure_compatibility_patch() {
  local repository=$1
  local patch_path=$2
  if git -C "${repository}" apply --reverse --check "${patch_path}" 2>/dev/null; then
    return 0
  fi
  if [[ ${verify_only} -eq 0 ]] && \
     git -C "${repository}" apply --check "${patch_path}" 2>/dev/null; then
    git -C "${repository}" apply "${patch_path}"
    return 0
  fi
  echo "Chipyard compatibility patch is not applied exactly: ${patch_path}" >&2
  return 4
}

if [[ ${verify_only} -eq 0 ]]; then
  required_submodules=(
    generators/boom
    generators/cva6
    generators/gemmini
    generators/hwacha
    generators/icenet
    generators/nvdla
    generators/riscv-sodor
    generators/rocket-chip
    generators/sha3
    generators/sifive-blocks
    generators/sifive-cache
    generators/testchipip
    sims/firesim
    tools/api-config-chipsalliance
    tools/barstools
    tools/chisel-testers
    tools/chisel3
    tools/dsptools
    tools/firrtl
    tools/firrtl-interpreter
    tools/rocket-dsp-utils
    tools/treadle
  )
  while read -r key _value; do
    git -C "${project_root}" config --unset-all "${key}" || true
  done < <(git -C "${project_root}" config --get-regexp '^submodule\..*\.update$' || true)
  git -C "${chipyard_root}" submodule update --init --depth 1 \
    --jobs "${AGENTSYS_JOBS:-4}" -- "${required_submodules[@]}"
  git -C "${chipyard_root}/generators/rocket-chip" submodule update --init \
    --depth 1 --jobs "${AGENTSYS_JOBS:-4}" -- \
    api-config-chipsalliance hardfloat
  git -C "${chipyard_root}/tools/barstools" submodule update --init \
    --depth 1 --jobs "${AGENTSYS_JOBS:-4}" -- mdf

  toolchain=${chipyard_root}/esp-tools-install
  compiler=${toolchain}/bin/riscv64-unknown-elf-gcc
  if [[ ! -x ${compiler} ]]; then
    seed=${AGENTSYS_RISCV_TOOLCHAIN_SEED:-}
    if [[ -z ${seed} ]]; then
      seed_compiler=$(command -v riscv64-unknown-elf-gcc || true)
      if [[ -n ${seed_compiler} ]]; then
        seed=$(realpath "$(dirname "${seed_compiler}")/..")
      fi
    fi
    if [[ -n ${seed} ]] && [[ -x ${seed}/bin/riscv64-unknown-elf-gcc ]]; then
      mkdir -p "${toolchain}"
      cp -a --reflink=auto "${seed}/." "${toolchain}/"
    else
      (
        cd "${chipyard_root}"
        bash scripts/build-toolchains.sh --ignore-qemu esp-tools
      )
    fi
  fi

  if [[ ! -f ${chipyard_root}/env.sh ]]; then
    touch "${chipyard_root}/env.sh"
  fi
  cat > "${chipyard_root}/env-esp-tools.sh" <<EOF
# Auto-generated by AgentSys bootstrap_chipyard.sh.
export CHIPYARD_TOOLCHAIN_SOURCED=1
export RISCV=$(printf '%q' "${toolchain}")
export PATH=\${RISCV}/bin:\${PATH}
export LD_LIBRARY_PATH=\${RISCV}/lib\${LD_LIBRARY_PATH:+":\${LD_LIBRARY_PATH}"}
EOF
  source_line="source $(printf '%q' "${chipyard_root}/env-esp-tools.sh")"
  grep -Fqx "${source_line}" "${chipyard_root}/env.sh" || \
    printf '%s\n' "${source_line}" >> "${chipyard_root}/env.sh"
fi

ensure_compatibility_patch \
  "${chipyard_root}/tools/chisel3" \
  "${project_root}/patches/chipyard/chisel3-stable-deps.patch"
ensure_compatibility_patch \
  "${chipyard_root}/tools/treadle" \
  "${project_root}/patches/chipyard/treadle-stable-firrtl.patch"

agentsys_require_chipyard_build "${chipyard_root}"
echo "AgentSys Chipyard ready: ${chipyard_root} ($(agentsys_chipyard_commit "${chipyard_root}"))"
